### ISSUE TITLE
Remove unused kernel(s) does not remove RC kernel(s) 

### ISSUE THREAD

**Issue by Ratko** [teejee2008/ukuu-plus#11]
Not big deal , but would be nice if Remove unused kernel(s) would remove RC kernel(s) to

**Comment by teejee2008** [comment]
Please provide more details.

Using the "Remove Unused kernels" button from main window will display all installed kernels. You can select and remove RC kernels from the list.

**Comment by phush0** [comment]
Also will not install RC kernels. Ukuu 19.04. If you try to install e.g.

` ukuu --user phusho --install 5.1.0-rc6
E: INVALID_INPUT: 5.1.0-rc6
E: Could not find requested kernel: 5.1.0
E: Run 'ukuu --list' to list available kernels
`

same for remove. If you install by hand it will show it correct.

**Comment by teejee2008** [comment]
Fixed in v19.05. Please update.
