### ISSUE TITLE
Exits on launch

### ISSUE THREAD

**Issue by fcmircea** [teejee2008/ukuu-plus#12]
Hello, trying to run 19.01 on Ubuntu 18.04.

The app starts, shows an "working in background" anim and then exits with no msg.

What do I need to attach where to find?

**Comment by teejee2008** [comment]
Is this on first launch? Make sure that you are connected to the internet when you start it.

Run `ukuu-gtk --debug` in a terminal and send me the output

**Comment by fcmircea** [comment]
Looks like after a reboot, everything works as expected.
