### ISSUE TITLE
Select number of old kernels to keep

### ISSUE THREAD

**Issue by viggy96** [teejee2008/ukuu-plus#13]
It would be cool if there were a way to select a number of old mainline kernels to keep. For example, I like to have the latest 3 mainline kernels installed, the current latest running one, and the two previous. right now I manually remove older ones by opening UKUU and clicking the '-' button to uninstall them. But it would be nice if this could be automated as well, just like the installation of new kernels. 

Also, I don't want UKUU to touch the official kernels from Canonical.

**Comment by teejee2008** [comment]
Added in v19.10
