### ISSUE TITLE
Have you seen this before?

### ISSUE THREAD

**Issue by myb120** [teejee2008/ukuu-plus#18]
DOWNLOAD_FAILED - http://kernel.ubuntu.com/~kernel-ppa/mainline/

List of kernels is more than 2 days old. Check your internet connectivity and restart the app to refresh the list.

**Comment by teejee2008** [comment]
This message was added in this version. It shows a warning if the list is outdated and cannot be refreshed. 

I'll be adding an option to turn off this warning in the next update.

**Comment by teejee2008** [comment]
This is changed in v19.04.1. Message will be shown only if download fails and index is older than 1 week.
