### ISSUE TITLE
Improve kernel publication notifications

### ISSUE THREAD

**Issue by jdferron** [teejee2008/ukuu-plus#21]
Currently, the application sends both toast notifications as well as a pop-up.  At times, this is very annoying as I am being told multiple times there is a new published kernel.   Also, the app will have multiple pop-ups stating there is a new kernel.

I am suggesting revisiting how this should work, all the user to select what types of notifications/pop-ups are shown, and how often they are shown.

**Comment by teejee2008** [comment]
This is fixed in v19.10. Notifications are less frequent and there is option to select between notification bubble/popup.
