### ISSUE TITLE
Error install kernel 5.20 in Ubuntu 18.04

### ISSUE THREAD

**Issue by pdus** [teejee2008/ukuu-plus#27]
Trying to install kernel 5.20, since the last 2 days, appears this message:
**E: This kernel cannot be installed as the build is broken. Please wait for the next kernel update.**

This issues it's from the Ubuntu PPA, and it will be fixed on the next days?. Or maybe it's an issue with Ukuu?.

Thanks

**Comment by Bookingyo** [comment]
I believe this is due to the 5.20 build for amd64 and i386 failed. You can see it under the https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2/

Once the builds are finalized and released it should fix the issue.

**Comment by pdus** [comment]
Thank you!. 

Yes, looking that link seems that you are right Bookingyo. I will check the link to know when it will be ready.

**Comment by cbartholomee** [comment]
Probably the same issue for 5.1.17 (?)

`ukuu --user c.bartholomee --install 5.1.17`
`----------------------------------------------------------------------`
`E: This kernel cannot be installed as the build is broken. Please wait for the next kernel update.`

**Comment by pdus** [comment]
Yes, I have the same issue with the same kernel. So seems that until Canonical doesn't solves this issue, in Ubuntu we couldn't update to 5.20 or 5.1.17. 

Wait and see...
