### ISSUE TITLE
Ukuu 19.07.3 can't install corrected mainline builds like 5.1.19 or 5.2.2

### ISSUE THREAD

**Issue by sahsanu** [teejee2008/ukuu-plus#30]
Hello,

I know there was a bug in gcc version used to compile the last kernels so these kernels didn't succeed to compile but right now, I've tested it with the new version 19.07.3 and it can't install mainline kernels like 5.1.19 or 5.2.2 and these kernels are now build with success...

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.1.19/ 
https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.2.2/ 

...but ukuu is still saying that kernels are broken.

Thank you in advance.

**Comment by sahsanu** [comment]
Nevermind, I removed the dir `/home/myuser/.cache/ukuu/5.2.2/ `and now it is working fine, seems ukuu cached the index page where the kernel didn't compile and ukuu is not trying to check whether the situation has changed for that kernel version.

**Comment by teejee2008** [comment]
Normally when builds are fixed on the server, the modified date changes on the main index page. This time the modification date remained the same, hence Ukuu could not detect that build status had changed. I need to find another way to detect that status has changed for a broken build.
