### ISSUE TITLE
[error] broken pipe

### ISSUE THREAD

**Issue by SoulInfernoDE** [teejee2008/ukuu-plus#31]
When i try to uninstall older kernels i get the following output:

> ukuu --user matze --remove 5.2.5
> ======================================================================
> Removing packages:
> ======================================================================
> Preparing to remove selected kernels
> 
> (Lese Datenbank ... 383476 Dateien und Verzeichnisse sind derzeit installiert.)
> Entfernen von linux-image-unsigned-5.2.5-050205-generic (5.2.5-050205.201907310632) ...
> /etc/kernel/prerm.d/dkms:
> dkms: removing: rtl88x2bu 5.3.1 (5.2.5-050205-generic) (x86_64)
> 
> -------- Uninstall Beginning --------
> Module:  rtl88x2bu
> Version: 5.3.1
> Kernel:  5.2.5-050205-generic (x86_64)
> -------------------------------------
> 
> Status: Before uninstall, this module version was ACTIVE on this kernel.
> 
> 88x2bu.ko:
>  - Uninstallation
>    - Deleting from: /lib/modules/5.2.5-050205-generic/kernel/drivers/net/
>  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> /usr/sbin/dkms: Zeile 2025: echo: Schreibfehler: Datenübergabe unterbrochen (broken pipe).
> /usr/sbin/dkms: Zeile 2027: echo: Schreibfehler: Datenübergabe unterbrochen (broken pipe).
> 
> depmod...
> 
> DKMS: uninstall completed.
> I: /vmlinuz.old is now a symlink to boot/vmlinuz-5.2.6-050206-generic
> I: /initrd.img.old is now a symlink to boot/initrd.img-5.2.6-050206-generic
> /etc/kernel/postrm.d/initramfs-tools:
> update-initramfs: Deleting /boot/initrd.img-5.2.5-050205-generic
> /etc/kernel/postrm.d/zz-update-grub:
> Sourcing file `/etc/default/grub'
> Sourcing file `/etc/default/grub.d/50_linuxmint.cfg'
> GRUB-Konfigurationsdatei wird erstellt …
> Linux-Abbild gefunden: /boot/vmlinuz-5.2.6-050206-generic
> initrd-Abbild gefunden: /boot/initrd.img-5.2.6-050206-generic
> Found memtest86+ image: /memtest86+.elf
> Found memtest86+ image: /memtest86+.bin
> Windows 7 auf /dev/sda1 gefunden
> erledigt
> Entfernen von linux-modules-5.2.5-050205-generic (5.2.5-050205.201907310632) ...
> Entfernen von linux-headers-5.2.5-050205-generic (5.2.5-050205.201907310632) ...
> dpkg: Warnung: Während Entfernens von linux-headers-5.2.5-050205-generic ist Verzeichnis »/lib/modules/5.2.5-050205-generic« nicht leer, wird daher nicht gelöscht
> Entfernen von linux-headers-5.2.5-050205 (5.2.5-050205.201907310632) ...
> 
> ======================================================================
> Running GRUB update:
> ======================================================================
> Updating GRUB menu
> Sourcing file `/etc/default/grub'
> Sourcing file `/etc/default/grub.d/50_linuxmint.cfg'
> GRUB-Konfigurationsdatei wird erstellt …
> Linux-Abbild gefunden: /boot/vmlinuz-5.2.6-050206-generic
> initrd-Abbild gefunden: /boot/initrd.img-5.2.6-050206-generic
> Found memtest86+ image: /memtest86+.elf
> Found memtest86+ image: /memtest86+.bin
> Windows 7 auf /dev/sda1 gefunden
> erledigt
> 
> Un-install completed

It seems after uninstalling kernel modules it's getting broken pipe errors. I don't know if that is bad or not.

--->> >  - Original module
>    - No original module was found for this module on this kernel.
>    - Use the dkms install command to reinstall any previous module version.
> /usr/sbin/dkms: Zeile 2025: echo: Schreibfehler: Datenübergabe unterbrochen (broken pipe).
> /usr/sbin/dkms: Zeile 2027: echo: Schreibfehler: Datenübergabe unterbrochen (broken pipe).

Is this normal?
Can it be fixed for future kernel removals?

**Comment by teejee2008** [comment]
This is normal. You can ignore these.
