### ISSUE TITLE
Ubuntu 16.04.6 / Kernel 2.6.32 can't ukuu --install-latest or any command

### ISSUE THREAD

**Issue by jefferson-1** [teejee2008/ukuu-plus#33]
Fresh 16.04.6 with Linux nagiosmonitor 2.6.32-042stab133.2 #1 SMP Mon Aug 27 21:07:08 MSK 2018 x86_64 x86_64 x86_64 GNU/Linux

Fresh install of Ukuu  
ukuu is already the newest version (19.07.5).
ukuu-assets is already the newest version (19.07.3).
ukuu-gtk is already the newest version (19.07.5).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

> Installed successfully

Any command just fails

root@nagiosmonitor:~# ukuu --install-latest
root@nagiosmonitor:~# ukuu --list
root@nagiosmonitor:~# ukuu --clean-cache
root@nagiosmonitor:~# ukuu -notify
E: Unknown option: -notify
E: Run 'ukuu --help' to list all options
root@nagiosmonitor:~# ukuu --notify
root@nagiosmonitor:~# ukuu -list-active
E: Unknown option: -list-active
E: Run 'ukuu --help' to list all options
root@nagiosmonitor:~# ukuu --list-active

It never prompted to install license key...

**Comment by jefferson-1** [comment]
[12:48:07.770] ukuu-gtk v19.07.5
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused

(ukuu-gtk:506): Gtk-WARNING **: cannot open display:

**Comment by jefferson-1** [comment]
To be fair...i only have shell (ssh) - no window so GTK will not work... I need something that works on SSH only.

**Comment by jefferson-1** [comment]
I got a VPS that loads Ubuntu 16.04 with that Kernel v2.6.32 and I'm trying to upgrade the Kernel.  No idea how to do it and I found your tool and now trying to upgrade the Kernel.

**Comment by teejee2008** [comment]
A VPS is a virtual system with many servers sharing the same kernel. It is not possible to change the kernel on such a system unless you are running a dedicated server.

**Comment by jefferson-1** [comment]
How can I tell that I can't upgrade the Kernel? I was able to copy Kernel files manually but I was having difficulty understanding which files to copy / install, etc.

**Comment by jefferson-1** [comment]
Okay...I contacted the VPS people and ... it is not possible to upgrade... Okay thanks.

**Comment by jefferson-1** [comment]
As a minor aside -- perhaps an error message indicating this issue would be useful rather than just a termination without any notes.
