### ISSUE TITLE
Ubuntu 18.04.3 LTS - Missing Commands Please install required packages

### ISSUE THREAD

**Issue by jefferson-1** [teejee2008/ukuu-plus#35]
root@jncla:~# ukuu
E: Missing commands. Please install required packages.
> pkexec
root@jncla:~#

I don't have desktop GUI installed yet but I ran ukuu-gtk for fun

root@jncla:~# ukuu-gtk
[12:13:23.668] ukuu-gtk v19.10.1
Unable to init server: Could not connect: Connection refused

(ukuu-gtk:918): Gtk-WARNING **: 12:13:23.701: cannot open display:

**Comment by teejee2008** [comment]
Install the package **policykit-1**. I'll remove the dependency from **aptik** in next update.

**ukuu-gtk** requires a display server/desktop to be installed. It will not run on headless systems. You can uninstall the **ukuu-gtk** package.

**Comment by jefferson-1** [comment]
TYVM
