### ISSUE TITLE
Support for secure boot

### ISSUE THREAD

**Issue by mkieblesz** [teejee2008/ukuu-plus#38]
Hi,
at the moment I cannot use downloaded kernels with secure boot turned on.

To go through signing process by myself I would have to mess with `/boot` directory, which is being updated by ukuu iteself. I find it too complex so I simply turned secure boot off - I ended up only with newly generated key for signing with `update-secureboot-policy --new-key`

Do you have any plans for supporting secure boot? If not, do you have simple instructions to deal with that process from ukuu perspective?

Thanks!

**Comment by teejee2008** [comment]
Adding support for secureboot is currently not possible. The mainline kernels installed by Ukuu are provided by Ubuntu. These are not signed as these are very new and not supported by the Ubuntu team.

Ukuu only downloads and installs these packages. It doesn't make any changes to the system.

For using with secureboot you need to generate a key manually and sign the kernels. Installing the key is a manual process that requires going into the MokManager at boot time and enrolling the key. You may face issues specific to your hardware (HP, Dell, etc) that need to be solved by searching on Google. This is not something that can be done by an application. It requires manual steps and troubleshooting by the end user.

**Comment by mkieblesz** [comment]
Cheers :+1:
