### ISSUE TITLE
ukuu --notify E: Unknown option: --notify

### ISSUE THREAD

**Issue by timrichardson** [teejee2008/ukuu-plus#40]
```
```
$ ukuu --nofify
E: Unknown option: --nofify
E: Run 'ukuu --help' to list all options
```
```
but

S```
yntax: ukuu <command> [options]

Commands:

  --list               List all kernels
  --list-installed     List installed kernels
  --list-active        List the active/running kernel
  --list-update        List new kernels
  --list-unused        List unused kernels
  --install <version>  Install specified mainline kernel
  --remove <version>   Remove specified kernel
  --download <version> Download packages for specified kernel
  --purge [x,y]        Remove installed kernels older than running kernel
                       x = official kernels to keep (def: 1), y = mainline kernels to keep (def: 2)
  --install-latest     Install latest kernel from latest series
  --clean-cache        Remove files from application cache
  --notify             Check for updates and notify current user
  --refresh            Force-check for new kernels (not needed)
  --hold-official      Hold updates for official kernel
  --unhold-official    Un-hold updates for official kernel
```

**Comment by teejee2008** [comment]
You have typed **nofify** instead of notify
