### ISSUE TITLE
Add support for ACS Override Kernels No Kernel can be removed or added when running

### ISSUE THREAD

**Issue by richard378** [teejee2008/ukuu-plus#44]
ACS Override Kernels are required for my motherboard to do vfio they can be found here: https://queuecumber.gitlab.io/linux-acs-override/
When I install them the ukuu paid version has trouble dealing with it.  It causes errors that no kernel can be added or removed when the ACS Override kernel is installed and running.

**Comment by teejee2008** [comment]
This app is meant to be used with Ubuntu's offical kernels and mainline kernels.

During system startup, press the arrow keys on your keyboard to enter GRUB boot menu. Go to advanced options and select any offical or mainline kernel from the list to boot the system.
