### ISSUE TITLE
Improvement: Start making use of Livepatch

### ISSUE THREAD

**Issue by olokos** [teejee2008/ukuu-plus#46]
Ubuntu is doing livepatch updates, maybe UKUU could integrate kernel updates using Livepatch mechanisms? 

I love keeping my sever up to date, but this eliminates me from the groups being proud of hundreds of days of uptime, not that it matters to me, but Livepatch does seem to be a good thing nonetheless.

I recall signing kernels and IMO this isn't something too difficult to achieve, can we try doing this?

**Comment by teejee2008** [comment]
Live patch is a _service_ provided by Canonical for their customers. They only support standard Ubuntu kernels since that's what their enterprise customers use. They have kept it free for home users for up to 3 machines, but it requires registration with Canonical to get the authentication token.

This is not something that can be built into an app.

**Comment by olokos** [comment]
Okay, in that case is there some other solution possible to keep kernel up-to-date without rebooting the system, to achieve better uptimes in the end?

**Comment by teejee2008** [comment]
Use Live patch with official kernels if you are worried about security and uptime.

Mainline kernels are bleeding-edge and untested. These not meant for production systems where reliability is a concern. Since these are untested, any upgrade can potentially cause problems.

**Comment by olokos** [comment]
@teejee2008 
I am fully aware of what you've said. yet I think it could be a real selling point for UKUU.

If this improvement was to be implemented and bleeding-edge and untested kernels could be applied using LivePatch, I am sure you would get a lot of recognition in the world, as there's no such solution available, but is it really impossible?

Currently I couldn't see any functionalities improvements over the public version as compared to this, paid one.

There was a command that allowed to --install-latest, now you need to specify kernel version yourself, in a paid version, which is supposed to be an improvement...
