### ISSUE TITLE
Error during installation of 5.4 series kernels

### ISSUE THREAD

**Issue by vdmit** [teejee2008/ukuu-plus#47]
All kernels of 5.4 series are installed with error:

"This kernel cannot be installed as the build is broken. Please wait for the next kernel update."

It's strange that all builds starting from 5.4.29 and further are broken (see screenshot attached).
More looks like an updater bug.

![image](https://user-images.githubusercontent.com/1774752/81178643-2fabe800-8fb1-11ea-8741-f01f21420fd9.png)

Other series are installed OK.
Ukuu version is 19.12.1.

**Comment by teejee2008** [comment]
Builds are indeed broken on the Ubuntu server

https://kernel.ubuntu.com/~kernel-ppa/mainline/v5.4.29/

If you check the above page the amd64 builds are marked as "build failed".

5.5x and 5.6x series are building successfully.
