### ISSUE TITLE
Failing on Ubuntu 16.04

### ISSUE THREAD

**Issue by mnkhan63** [teejee2008/ukuu-plus#48]
I am getting this error on Ubuntu 16.04.  Somehow it is looking for  libssl1.1 (>= 1.1.0).  The same kernel can be installed manually without any errors.

The following packages have unmet dependencies:
 linux-headers-5.6.11-050611-generic : Depends: libssl1.1 (>= 1.1.0) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by teejee2008** [comment]
Install the libssl package from following link:
http://mirrors.kernel.org/ubuntu/pool/main/o/openssl/libssl1.1_1.1.0g-2ubuntu4_amd64.deb
