### ISSUE TITLE
E: Packages are missing in PPA for this kernel version (arch=amd64, flavor=generic)

### ISSUE THREAD

**Issue by MasterCATZ** [teejee2008/ukuu-plus#50]
Ever since 5.7.1 / 5.6.17 this error happens how do I  correct it ? 

E: Packages are missing in PPA for this kernel version (arch=amd64, flavor=generic)

**Comment by teejee2008** [comment]
Which version are you using? Update to v20.06 and click the Refresh button on the main window.

**Comment by MasterCATZ** [comment]
v19.12.1 

I can not seem to find any update ? 

Please run the following command in a terminal window. This will install Ukuu and add a repository for receiving future updates.

wget -O - https://teejeetech.com/install-ukuu-8ALv9hCkUG.sh | bash

**Comment by teejee2008** [comment]
Did you by any chance upgrade to the next Ubuntu release? External repositories sometimes get disabled during the OS upgrade.
