### ISSUE TITLE
ukuu --purge fails to remove unused old kernels

### ISSUE THREAD

**Issue by olokos** [teejee2008/ukuu-plus#51]
```kiepownica@kiepownica:~$ sudo ukuu --purge

Following kernels will be removed:
 -> v5.6.11
 -> v5.6.7
 -> v5.6.6
 -> v5.3.0.32
 -> v5.3.0.15

Continue ? (y/n): y
======================================================================
Removing packages:
======================================================================
Preparing to remove selected kernels
E: Could not find the packages to remove!
```

**Comment by olokos** [comment]
This is an ongoing issue
```
kiepownica@kiepownica:~$ sudo ukuu --purge 1,2

Following kernels will be removed:
 -> v5.6.11
 -> v5.6.7
 -> v5.6.6
 -> v5.3.0.34
 -> v5.3.0.32
 -> v5.3.0.17

Continue ? (y/n): y
======================================================================
Removing packages:
======================================================================
Preparing to remove selected kernels
E: Could not find the packages to remove!
```

It does install new kernels, but doesn't remove any.

**Comment by olokos** [comment]
@teejee2008

**Comment by teejee2008** [comment]
I was not able to reproduce this issue. Which version of Ukuu are you using?

**Comment by olokos** [comment]
@teejee2008 
```
kiepownica@kiepownica:~$ ukuu --help

Ukuu Kernel Update Utility v20.06.2 by Tony George (teejeetech@gmail.com)
```
As far as I am aware, this is the latest version from the paid PPA.

**Comment by teejee2008** [comment]
You are on the latest version.

The app is not able to find packages for one of the kernels in list. Please send me the output of following command:
`sudo ukuu --purge 1,1 --debug`

**Comment by olokos** [comment]
@teejee2008 
Here it is https://pastebin.com/YivJU7tY

Sorry about late reply, I missed the notification somehow.

**Comment by teejee2008** [comment]
You seem to be using the GKE variant of official kernels. It is not currently supported by the app. I'll add support for it in the next update.

**Comment by olokos** [comment]
I did not install any specific version of a kernel, I've been using ukuu for about 2 years now, even before it went paid.

**Comment by teejee2008** [comment]
Some of the official kernels on your system are of GKE variant (Google Kubernetes Engine). Package names have -gke suffix.

linux-image-5.3.0-1034-gke

This is a variant of the official kernel that is meant to be used on cloud instances. It may have been installed accidentally. You can try removing the packages manually and installing the generic kernels from Ubuntu repository.

**Comment by olokos** [comment]
Hello,

It either was installed automatically by `apt upgrade` or by ukuu

I could wait for an update to UKUU, if it could be done in a reasonable timeframe.

Other than that, ukuu --purge is meant to remove the kernel itself and its headers? or is there something more to it?

**Comment by teejee2008** [comment]
Which Linux distribution are you using? Some distributions include the GKE kernels if it is meant to be used on cloud instances.

Ukuu does not install official kernels. It downloads and installs packages for mainline kernels from the Ubuntu server.

You can install the generic kernel and remove packages for Gke kernel with following commands:

sudo apt install linux-image-generic
sudo apt purge linux-gke linux-image-gke

**Comment by olokos** [comment]
Ubuntu 18.04

I tried above commands
First one says that linux-image-generic is already in latest version
second one says no package found, so I added a wildcard at the end of gke for both packages and this resulted in the following
```
The following additional packages will be installed:
  dkms wireguard-dkms
Sugerowane pakiety:
  menu
Następujące pakiety zostaną USUNIĘTE:
  linux-image-gke-5.3*
Zostaną zainstalowane następujące NOWE pakiety:
  dkms wireguard-dkms
0 aktualizowanych, 2 nowo instalowanych, 1 usuwanych i 0 nieaktualizowanych.
Konieczne pobranie 318 kB archiwów.
Po tej operacji zostanie dodatkowo użyte 2 042 kB miejsca na dysku.
Kontynuować? [T/n]
Pobieranie:1 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 dkms all 2.3-3ubuntu9.7 [68,1 kB]
Pobieranie:2 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 wireguard-dkms all 1.0.20200611-1ubuntu1~18.04.1 [250 kB]
Pobrano 318 kB w 0s (1 403 kB/s)
Wybieranie wcześniej niewybranego pakietu dkms.
(Odczytywanie bazy danych ... 410188 plików i katalogów obecnie zainstalowanych.)
Przygotowywanie do rozpakowania pakietu .../dkms_2.3-3ubuntu9.7_all.deb ...
Rozpakowywanie pakietu dkms (2.3-3ubuntu9.7) ...
Wybieranie wcześniej niewybranego pakietu wireguard-dkms.
Przygotowywanie do rozpakowania pakietu .../wireguard-dkms_1.0.20200611-1ubuntu1~18.04.1_all.deb ...
Rozpakowywanie pakietu wireguard-dkms (1.0.20200611-1ubuntu1~18.04.1) ...
dpkg: linux-image-gke-5.3: problemy z zależnościami, usuwanie według żądania:
 wireguard zależy od wireguard-dkms (>= 0.0.20200121-2) | wireguard-modules (>= 0.0.20191219); jednakże:
  Pakiet wireguard-dkms nie jest jeszcze skonfigurowany.
  Pakiet wireguard-modules nie jest zainstalowany.
  Pakiet linux-image-gke-5.3 dostarcza wireguard-modules, ale jest przeznaczony do usunięcia.

(Odczytywanie bazy danych ... 410389 plików i katalogów obecnie zainstalowanych.)
Usuwanie pakietu linux-image-gke-5.3 (5.3.0.1036.20) ...
Konfigurowanie pakietu dkms (2.3-3ubuntu9.7) ...
Konfigurowanie pakietu wireguard-dkms (1.0.20200611-1ubuntu1~18.04.1) ...
Loading new wireguard-1.0.20200611 DKMS files...
Building for 5.7.6-050706-generic
Building initial module for 5.7.6-050706-generic
Error!  The dkms.conf for this module includes a BUILD_EXCLUSIVE directive which
does not match this kernel/arch.  This indicates that it should not be built.
Skipped.
Przetwarzanie wyzwalaczy pakietu man-db (2.8.3-2ubuntu0.1)...
kiepownica@kiepownica:~$
```

**Comment by olokos** [comment]
kiepownica@kiepownica:~$ sudo ukuu --purge

Following kernels will be removed:
 -> v5.6.11
 -> v5.6.7
 -> v5.6.6
 -> v5.3.0.38

Continue ? (y/n): y
======================================================================
Removing packages:
======================================================================
Preparing to remove selected kernels
E: Could not find the packages to remove!

Even after manual removal of the gke kernels - `ukuu` fails to `--purge` sadly.

**Comment by olokos** [comment]
I've done one more attempt with
`apt purge *-gke`
that did eventually remove all GKE kernels and ukuu works again.

Hopefully support for GKE could be added in the future.
