### ISSUE TITLE
Key not certified with a trusted signature.

### ISSUE THREAD

**Issue by KoenDG** [teejee2008/ukuu-plus#52]
I'm getting the following message when trying to install a new kernel version:

```
17:11:14 #  ukuu --user myuser --install 4.19.133
======================================================================
Verifying packages:
======================================================================
Checking signature...


gpg: Signature made Thu 16 Jul 2020 09:36:56 AM CEST
gpg:                using RSA key E50C6A0917C622B0
gpg: Good signature from "Kernel PPA <kernel-ppa@canonical.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 60AA 7B6F 3043 4AE6 8E56  9963 E50C 6A09 17C6 22B0

Signature verified successfully
----------------------------------------------------------------------
Checking checksums...


No packages were found for this kernel
```

Tried hunting down the new key but no luck so far.

Please advise.

**Comment by teejee2008** [comment]
Signature is not the problem. It was verified successfully. The warning regarding trusted signature can be ignored.

Which version of Ukuu are you using and which distribution? I did not get any errors on installing kernel 4.19.133 on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/12488854/87804695-dd6d2a00-c871-11ea-87a1-d5e369839c87.png)

Try clearing the cache and install again (Settings > Advanced > Clean cache)

**Comment by KoenDG** [comment]
I'm running Ubuntu 18.04, Ukuu version 19.01

Which turned out to be the problem. I had completely missed the email about the repository. I'm on 20.06.2 now, install worked as expected.

Thanks for your time.
