### ISSUE TITLE
On Linuxmint 20 - what packages should not be updated with a new 5.7 kernel ?

### ISSUE THREAD

**Issue by Moody1021** [teejee2008/ukuu-plus#53]
Linuxmint update manager has a kernel and base update for 5.4 kernels. This would presumably negate the upgraded kernel via ukuu. What other packages should not be updated so as not to interfere with the new 5.7 kernel.

**Comment by teejee2008** [comment]
You can install the updates for the 5.4 kernel. Grub always boots the latest kernel that is installed, so it will boot the 5.7 kernel.
