### ISSUE TITLE
Kernel 5.9.7 not in ppa

### ISSUE THREAD

**Issue by mradeschnig** [teejee2008/ukuu-plus#54]
My installation of ukuu shows Kernel 5.9.7  in the lsit, but can not install it:
I get following message (user is replaced by #myuser#):
 ukuu --user #myuser# --wget --install 5.9.7
E: Packages are missing in PPA for this kernel version (arch=amd64, flavor=generic)
I use ukuu 20.062 on Ubuntu 20.04.1 LTS. Kernel 5.9.6 was no problem to install.

**Comment by ronnocnave** [comment]
Hello. This happens occasionally when the mainline kernel does not compile properly. It is not an issue in the software, but rather in the packaging.

On November 10, 2020 10:03:17 AM EST, mradeschnig <notifications@github.com> wrote:
>My installation of ukuu shows Kernel 5.9.7  in the lsit, but can not
>install it:
>I get following message (user is replaced by #myuser#):
> ukuu --user #myuser# --wget --install 5.9.7
>E: Packages are missing in PPA for this kernel version (arch=amd64,
>flavor=generic)
>I use ukuu 20.062 on Ubuntu 20.04.1 LTS. Kernel 5.9.6 was no problem to
>install.
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/teejee2008/ukuu-plus/issues/54

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by mradeschnig** [comment]
So you think it is the mianline repository, or can I modify anything in my environment?

**Comment by ronnocnave** [comment]
It is the repository. You really can't do anything except wait for the next point release to be built. This seems to happen once every few months. Not sure what causes it, but there's really nothing you can do on your end.

On November 10, 2020 11:30:02 AM EST, mradeschnig <notifications@github.com> wrote:
>So you think it is the mianline repository, or can I modify anything in
>my environment?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/teejee2008/ukuu-plus/issues/54#issuecomment-724815258

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.
