### ISSUE TITLE
No internet connection to internet connected...

### ISSUE THREAD

**Issue by robotard** [teejee2008/ukuu-plus#55]
Probs an edge case, but also probs not a great amount of work considering it's now a paid for product (which work nicely btw), but when starting the app with no internet connection (my wifi decided to disconnect temporarily), you receive a message about no connection, but when you've then got a live connection the app doesnt offer anything but a circular icon in the middle...

Could do with a clickable "please try again" button, or even better would be to implement a network monitor that would also help with handling downloading new kernels etc...

Thanks TJ, and deffo worth the purchase (don't listen to the haters... Would be cool to have a contribute option for those that actually did wanna help you with the workload too)

**Comment by teejee2008** [comment]
I'll add some changes for this in the next release

**Comment by robotard** [comment]
Thanks TeeJee. Not gonna lie, was definitely worth the purchase 👍
