### ISSUE TITLE
No Eathernet and no Wifi

### ISSUE THREAD

**Issue by Mohamedaminhamdad** [teejee2008/ukuu-plus#56]
Since I didn't have Wifi connection (Wifi 6) on Ubuntu 16.04 kernel 4.15 I've decided to update the kernel by myself. 
after going for 5.4. I don't have any internet access now, neither WiFi nor Eathernet. While installing kernel 5.4 an Error occurred with the i backport-iwlwifi-8042   When I consulted the adress listed there I got the following file attached. 
Can someone help me how to fix that? do you need something else I should upload. 

[make.log](https://github.com/teejee2008/ukuu-plus/files/5608498/make.log)

**Comment by teejee2008** [comment]
Ubuntu 16.04 is very old. Please consider moving to a newer Ubuntu release.

Press SHIFT while your system is booting to enter the Grub boot menu. Then select "Advanced options" and select the older 4.15 kernel for booting. Once the system has booted, remove the new kernel that is causing problems.

https://askubuntu.com/a/1161432
