### ISSUE TITLE
Add support for Anbox by enabling ashmem and binder

### ISSUE THREAD

**Issue by SoulInfernoDE** [teejee2008/ukuu-plus#61]
Hello since newer kernels changed a routine for security reasons and included the ashmem and binder modules into the kernel it needs to be enabled and built with the kernel by default.
Could you include this in ukuu plus as referenced here:
https://github.com/anbox/anbox-modules/issues/49

And here (my issue request) 
https://github.com/anbox/anbox-modules/issues/75

best regards

**Comment by teejee2008** [comment]
This is outside the scope of the project. The mainline kernels are not built by me. These are built by Ubuntu using the upstream kernel sources. UKUU downloads the kernel packages from Ubuntu's servers and installs them on your system.

**Comment by choff** [comment]
Hello @SoulInfernoDE ,

according to this page: https://docs.anbox.io/userguide/install_kernel_modules.html ashmem and binder should be included in the Ubuntu kernel since Ubuntu 19.04.


Best regards,

   Christian

**Comment by SoulInfernoDE** [comment]
Hey Tony,
okay the idea was if you may could include a build yourself button in the app where ukuu could download needed dependencies etc.. 
Would be a nice extra feature.

**Comment by teejee2008** [comment]
> okay the idea was if you may could include a build yourself button in the app where ukuu could download needed dependencies etc..

It's not that simple. The build can fail for any number of reasons and you need to troubleshoot the errors on a case-by-case basis.

**Comment by SoulInfernoDE** [comment]
Hmh yes that's true,
:-/

Would be still a nice starting help for special cases. Maybe it could be mentioned that it most likely would fail.
