### ISSUE TITLE
ukuu --purge Error: Could not find the packages to remove!

### ISSUE THREAD

**Issue by olokos** [teejee2008/ukuu-plus#63]
![image](https://user-images.githubusercontent.com/1755581/147867582-8f6f0103-31e3-495e-af38-64bc4d6c3f1f.png)

That's the error I'm getting when trying to remove old kernels

**Comment by teejee2008** [comment]
what is the type of the linux kernel for 5.4.0.91.95 ? You can check with "sudo apt list --installed | grep linux-image".

**Comment by olokos** [comment]
![image](https://user-images.githubusercontent.com/1755581/147867573-e0e34782-739c-4896-a6f4-d71e3839c2be.png)

@teejee2008

**Comment by teejee2008** [comment]
The kernel you are trying to remove is the last official kernel on your system. Atleast one official kernel must be installed. Trying to remove all of them can break the system due to package dependencies. I'll update the error message to make it more clear.

**Comment by olokos** [comment]
That's totally fine, but why I cannot remove the rest of the kernels?

It's completely fine if the 5.4.0-91 kernel remains, but why I can't remove any other kernels anymore?... :(

They just keep growing with each update I make at this point.

**Comment by teejee2008** [comment]
Please update to v22.01 and let me know if it fixes the issue.

**Comment by olokos** [comment]
![image](https://user-images.githubusercontent.com/1755581/148845216-add12ba2-7a6c-4ea6-ae20-e99f2b8cb4f6.png)

While it's an improvement, I'm not sure if that's how it's meant to work?
It doesn't really remove a lot of old kernels for some reason.

**Comment by teejee2008** [comment]
This is strange. What is the output of "sudo ukuu --purge --debug" ?

**Comment by teejee2008** [comment]
The packages marked as "rc" in the output of "dpkg --list" are not actually installed. "rc" indicates that packages are not installed but some configuration files are present. 

Only 5.15.4/5/6/8/10/12 are installed. Purge will keep 2 mainline kernels and 1 official kernel by default. Let me know in case this is still not clear. You can run "sudo ukuu --list-installed" to get the list of installed kernels.

**Comment by olokos** [comment]
Everything works as expected, very nice!

If you don't mind then I'll remove above screenshots for security purposes.

Also, what was changed in the second update for ukuu you pushed to ppa? (latest update)
Possibly GKE kernels were fixed?

**Comment by teejee2008** [comment]
Latest update has a work-around for installing kernel 5.16. v5.16 has multiple packages on the Ubuntu server because of which installation was failing.
