### ISSUE TITLE
"Clearsigned file isn't valid, got 'NOSPLIT'" error when trying to fetch updates

### ISSUE THREAD

**Issue by Random-Chain** [teejee2008/ukuu-plus#65]
````
-- removed
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
````

**Comment by teejee2008** [comment]
Please don't post the repo urls here.

This is a network error that is shown when Apt is not able to download some of the repository files.

Your internet connection seems to be unreliable. Try connecting to another network.
