### ISSUE TITLE
'Terminal busy' error (as reported previously by private e-mail)

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [teejee2008/ukuu-plus#8]
After I run Ukuu, the first time I attempt an installation or removal I get an error about a process being busy in a terminal.
![image](https://user-images.githubusercontent.com/47056543/52687229-e1906c00-2f48-11e9-93a2-0ad51d1b2b21.png)

The second time I attempt the job, it works.

**Comment by teejee2008** [comment]
This will be fixed in the next update

**Comment by teejee2008** [comment]
Fixed in v19.04
