### ISSUE TITLE
Ubuntu Software Upgrader keeps wanting to remove UKUU

### ISSUE THREAD

**Issue by viggy96** [teejee2008/ukuu-plus#9]
The Ubuntu 'Software Upgrader' keeps wanting to remove the premium UKUU, and go back to the free one, with a 'partial upgrade'. I believe this might have something to do with the PPA I have added, which I also use for your other software, Timeshift. Ubuntu wants to downgrade me from this paid version to an older UKUU from that repo. I don't want to remove that repo because I want to get updates for Timeshift.

While for more advanced users this minor annoyance is fine, for less experienced users, which this software should be intended for, this issue should be resolved somehow.

**Comment by teejee2008** [comment]
The paid version (v19.01) is newer than the free version in PPA (v18.9). There's no reason for the software updater to attempt to downgrade packages.

No other users have reported this issue so far, so it may be something specific to your system.

Please provide the exact message or some screenshots for better understanding.

**Comment by viggy96** [comment]
![screenshot from 2019-02-20 00-31-12](https://user-images.githubusercontent.com/9837626/53073374-dc39a100-34b5-11e9-89f1-7f10895236ab.png)
![screenshot from 2019-02-20 00-38-29](https://user-images.githubusercontent.com/9837626/53073376-de9bfb00-34b5-11e9-9e91-f3c911f02088.png)

**Comment by viggy96** [comment]
Comparable messages when doing `apt dist-upgrade`.

**Comment by teejee2008** [comment]
Let me know which distribution you are using. I was not able to reproduce this on Ubuntu 18.04.

I have set up a new PPA for Timeshift. You can remove the existing PPA and add this one.
```
sudo add-apt-repository ppa:teejee2008/timeshift
sudo apt-get update
```

**Comment by viggy96** [comment]
I am using Ubuntu 18.04 LTS.

**Comment by viggy96** [comment]
Thanks, removing the old PPA, and adding the PPA for Timeshift fixed the issue. I no longer get the messages above.
